# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: sebo_development
  pool: 5
  username: postgres
  password: please

test: &test
  adapter: postgresql
  encoding: unicode
  database: sebo_test
  pool: 5
  username: postgres
  password: please

production:
  adapter: postgresql
  encoding: unicode
  database: sebo_production
  pool: 5
  username: anthony
  password:

cucumber:
  <<: *test